### ISSUE TITLE
Support GitLab ambient credentials 

### ISSUE THREAD

**Issue by jku** [di/id#121]
sigstore-python top-level issue https://github.com/sigstore/sigstore-python/issues/31

Gitlab has a slightly unique take on ambient credentials (https://docs.gitlab.com/ee/ci/secrets/id_token_authentication.html, https://docs.gitlab.com/ee/ci/yaml/signing_examples.html). There is no API to fetch the token but the token generation is part of the pipeline definition and the token is exposed in a environment variable:

```
sign_artifact:
  stage: build
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - command_that_uses_SIGSTORE_ID_TOKEN_env_variable
```

This doesn't map that well with the design in di/id (as id cannot ask for a token with a specific audience, but has to find a already defined env variable) so I'll just throw some ideas out there:
* one option is to add a generic `detect_env_var(audience: str)` that would use a well-known variable like `DI_ID_TOKEN` to look up the token and expect the user to use that variable name in their pipeline-- this has the disadvantage that the token env variable name is not tied to the audience: so you are limited to using one token per job even though gitlab supports multiple
* One could also do that same thing but use the audience as postfix for the env variable name: if the detector is called with audience="sigstore" it would look for `DI_ID_TOKEN_sigstore` variable -- this has some obvious issues with incompatible characters in the audience string. 
* it looks like cosign supports the specific `SIGSTORE_ID_TOKEN` variable name out of the box so I suppose a possible hack is to support only the "sigstore" audience (and then only look for the hard coded variable name `SIGSTORE_ID_TOKEN`)

None of these sound especially good (and I've not tried them yet). Maybe someone else comes up with another idea?

**Comment by di** [comment]
Galaxy brain idea: we write a `def detect_gitlab(audience: str)` function that looks at _every_ environment variable, sees if any are JWTs, and then sees if any of those match the requested audience, if not, throw an error. I think the edge case we'd have to handle if there are multiple tokens with the same audience, but not sure if that is possible on Gitlab's side.

Probably a more reasonable approach: something like your 3rd option, but we look for `<AUDIENCE>_ID_TOKEN`, so this works with the audience `sigstore` and the `SIGSTORE_ID_TOKEN` out of the box.

We should look and see how/if cosign does ambient credential detection for Gitlab and see if there's anything we can borrow.

**Comment by jku** [comment]
> We should look and see how/if cosign does ambient credential detection for Gitlab and see if there's anything we can borrow.

I believe it's literally a "env var token provider" that reads the token from SIGSTORE_ID_TOKEN:
https://github.com/sigstore/cosign/tree/main/pkg/providers/envvar

**Comment by di** [comment]
Makes sense. So given that this library is not intended to be sigstore-specific, looking for `<AUDIENCE>_ID_TOKEN` seems to make sense to me.

**Comment by woodruffw** [comment]
> Makes sense. So given that this library is not intended to be sigstore-specific, looking for <AUDIENCE>_ID_TOKEN seems to make sense to me.

Agreed with this; I like the galaxy brain idea but establishing a slight convention of `<AUDIENCE>_ID_TOKEN` on GitLab is probably more reasonable 🙂
